name: Starchild Chocolate
favicon: null
layout_spectrum: 0.91711
typography_spectrum: 0.48069
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#040402'
    - '#583023'
    - '#935e25'
    - '#d4a85d'
    - '#d0cac0'
  brandStrength: 0.29949459759518504
  lightness: 0.5625
  saturation: 0.1875
  rhythmicContrast: 0.5
purpose: []
